---
apiVersion: v1
kind: Namespace
metadata:
  name: ignite-web-console

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: regcred
#   namespace: ignite-web-console
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: {{ printf "{}" | b64enc }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: ignite-web-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
      - image: {{ printf "%s%s%s" .Values.repository "/web-console-backend:" .Values.version }}
        name: backend
        resources: {}
        env:
          - name: mail_auth_pass
          - name: mail_auth_user
          - name: mail_from
          - name: mail_greeting
          - name: mail_service
          - name: mail_sign
          - name: mongodb_url
            value: mongodb://mongodb.ignite-web-mongodb.svc.cluster.local/console
          - name: server_host
            value: "0.0.0.0"
          - name: server_port
            value: "3000"
          - name: server_sessionSecret
            value: "SERVER_SESSION_SECRET"
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: backend
  namespace: ignite-web-console
  labels:
    app: backend
spec:
  ports:
  - name: "backend"
    port: 3000
    targetPort: 3000
  selector:
    app: backend
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
  namespace: ignite-web-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      imagePullSecrets:
       - name: regcred
      containers:
      - image: {{ printf "%s%s%s" .Values.repository "/web-console-frontend:" .Values.version }}
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend
  namespace: ignite-web-console
  labels:
    app: frontend
spec:
  ports:
  - name: "frontend"
    port: 80
    targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
