apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-agent
  namespace: ignite
spec:
  selector:
    matchLabels:
      app: web-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: web-agent
    spec:
      serviceAccountName: ignite
      imagePullSecrets:
      - name: regcred
      containers:
      - name: web-agent
        image: {{ printf "%s%s%s" .Values.repository "/web-agent:" .Values.version }}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: DRIVER_FOLDER
          value: "./jdbc-drivers"
        - name: NODE_URI
          value: "http://ignite.ignite.svc.cluster.local:8080"
        - name: SERVER_URI
          value: "http://frontend.ignite-web-console.svc.cluster.local"
        - name: TOKENS
          value: "WEB_TOKEN"
        - name: NODE_LOGIN
          value: web-agent
        - name: NODE_PASSWORD
          value: password
