{
    "apiVersion": "storage.k8s.io/v1",
    "kind": "StorageClass",
    "metadata": {
        "name": "ignite-persistence-storage-class",
        "namespace": "ignite"
    },
    "provisioner": {{ .Values.storage_class_provisioner }},
    "parameters": {{ .Values.storage_class_parameters | toJson }}
}