{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "name": "ignite",
        "namespace": "ignite"
    },
    "spec": {
        "ports": [
            {
                "name": "rest",
                "port": 8080,
                "targetPort": 8080
            },
            {
                "name": "sql",
                "port": 10800,
                "targetPort": 10800
            },
            {
                "name": "thinclients",
                "port": 10900,
                "targetPort": 10900
            }
        ],
        "selector": {
            "app": "ignite"
        },
        "sessionAffinity": "ClientIP",
        "type": "LoadBalancer"
    }
}